server:
  shutdown: graceful
spring:
  application:
    name: avios
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:h2:mem:aviosdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

# TODO     comfigure and tune hystrix, hibernate, hikari etc etc
